apiVersion: batch/v1
kind: Job
metadata:
  name: iotmqttdm-job
  namespace: aro-workshop
spec:  
  template:    
    spec:      
      containers:
        - name: iotmqttdm-pod
          image: arowkshacr.azurecr.io/iotmqttdm:v1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: iotmqtt-sender-secret
      restartPolicy: Never