apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iotmqttdm-crjob
  namespace: aks-workshop-dev
spec:
  schedule: "0 */2 */7 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: iotmqttdm-pod
              image: akswkshpacr.azurecr.io/iotmqttdm:v1.0.3
              imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: aks-workshop-secret
          restartPolicy: OnFailure